### ISSUE TITLE
pandana revamp todo list

### ISSUE THREAD

**Issue by fscottfoti** [UDST/pandana#83]
I'm opening an issue to keep track of my to do list for the pandana rewrite taking place [here](https://github.com/UDST/pandana/tree/cython)

The main purpose of the rewrite is to replace the C++ api wrapper pyaccesswrap.cpp with a cython wrapper which will be much easier to use going forward.  Cython was around when I worked on this but it wasn't nearly as ubiquitous  as it is these days.

In addition to that I should be able to fix:
* style issues and general clunkiness in the C++ code
* use scipy NN instead of ANN, which saves us from having to build ANN
* the big one: not having global memory thus allowing Accessibility objects to be created and discarded on the fly #52 

Here's the ongoing high level todo list:
- [x] port POI functions to cython
- [x] port aggregation functions to cython
- [x] port shortest path and precompute functions to cython
- [x] integrate with @federicofernandez scipy NN code
- [x] add unit tests for the cython wrapper (lower level tests)
- [x] get the old unit tests back up and running again

Small issues:
- [x] make sure #73 is still solved
- [x] check to see if nodes ids and locations are actually used in CH code - I don't think they are and can be removed from cython wrapper
- [x] addGraphalg doesn't have to be public - cython shouldn't know about graphAlg
- [x] think long and hard about which level is responsible for turning ids into indexes (CH requires indexes), in the context of #62 
- [x] drop initialize_pois - use std::map internally, use strings for categories
- [x] drop initialize_acc_vars - use std::map internally, use strings for categories
- [x] pass in strings for decay and aggregation types, rather than ints
- [x] impedance ids should be strings not ints too (leaving this as-is)
- [x] check for memory leaks
- [x] add test for non integer node ids
- [x] there's probably a better way to return the POI node_ids
- [x] fix travis build issue for python3.5

**Comment by fscottfoti** [comment]
finished with https://github.com/UDST/pandana/pull/87
